### ISSUE TITLE
Please remove from public availability

### ISSUE THREAD

**Issue by cfolson** [jrchheng/hw#2]
Could you please remove your CSS 487 code from public availability. I am teaching the course again this fall and I don't want the code available to the new students.
Thanks,
Clark Olson

**Comment by jrchheng** [comment]
Done.

**Comment by cfolson** [comment]
Thanks. Unfortunately, this has started become an issue in some classes.

**Comment by jrchheng** [comment]
No problem. I just got my student subscription extended so I can make the entire repo private.
